name: build

on:
  workflow_dispatch:
  
jobs:
  build:
    #runs-on: self-hosted
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        alpine: [3.18]
        clamav: [0.103.8, 0.104.4, 0.105.2, 1.0.1, 1.1.0]
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          build-args: |
            ALPINE=${{ matrix.alpine }}
            CLAMAV=${{ matrix.clamav }}
          push: true
          platforms: linux/amd64,linux/arm/v7,linux/arm64/v8
          tags: |
            ghcr.io/bfren/clamav:${{ matrix.clamav }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
